/**
 * @eclia/symphony-protocol
 *
 * Wire types shared between the Symphony engine and its clients
 * (web-console, API consumers).  No runtime code.
 */

// ─── Port system ────────────────────────────────────────────

export type PortType = "any" | "string" | "object" | "boolean" | "number";

/** Maps ConfigFieldSchema.type → PortType for connectable config fields. */
export const CFG_TO_PORT: Record<string, PortType>;

export interface PortDef {
  key: string;
  label: string;
  type: PortType;
  optional?: boolean;
  /** Config key whose value determines the actual port type at design time. */
  typeFrom?: string;
  /** Input port key(s) on the same node whose resolved type this output mirrors.
   *  Array form: all referenced ports must agree on the same concrete type;
   *  if they disagree the output stays "any". */
  typeFromPort?: string | string[];
  /** Known top-level keys for object-type ports, mapped to their types.
   *  Used by Parse node to auto-generate typed output ports when connected. */
  objectKeys?: Record<string, PortType>;
}

// ─── Node metadata ──────────────────────────────────────────

export type NodeRole = "source" | "process" | "action" | "gate";

export interface ConfigFieldSchema {
  key: string;
  label: string;
  type: "string" | "number" | "boolean" | "text" | "select" | "model";
  required?: boolean;
  default?: unknown;
  placeholder?: string;
  sensitive?: boolean;
  options?: string[];
  /** If true, this field also appears as an input port. Wired values override config. */
  connectable?: boolean;
}

/** Template for dynamic port creation — declared on the schema, instances live on OpusNodeDef. */
export interface DynamicPortTemplate {
  type: PortType;
  labelPrefix: string;
  /** If true, ports are auto-generated by the system (e.g. Parse from objectKeys),
   *  not user-managed via +/− buttons. */
  auto?: boolean;
}

/** Schema for a registered node kind, returned by GET /nodes. */
export interface NodeKindSchema {
  kind: string;
  label: string;
  role: NodeRole;
  description?: string;
  inputPorts: PortDef[];
  outputPorts: PortDef[];
  configSchema: ConfigFieldSchema[];
  /** If present, users can add/remove input ports on instances of this kind. */
  dynamicInput?: DynamicPortTemplate;
  /** If present, users can add/remove output ports on instances of this kind. */
  dynamicOutput?: DynamicPortTemplate;
}

// ─── Opus definition ────────────────────────────────────────

export interface OpusDef {
  id: string;
  name: string;
  enabled: boolean;
  nodes: OpusNodeDef[];
  links: OpusLinkDef[];
  ui?: OpusUiMeta;
}

export interface OpusNodeDef {
  nid: string;
  kind: string;
  config: Record<string, unknown>;
  /** Per-instance dynamic input ports (user-managed or auto-generated at design time). */
  dynamicInputs?: PortDef[];
  /** Per-instance dynamic output ports (user-managed or auto-generated at design time). */
  dynamicOutputs?: PortDef[];
}

export interface OpusLinkDef {
  lid: string;
  from: string;
  fromPort: string;
  to: string;
  toPort: string;
}

export interface OpusUiMeta {
  positions?: Record<string, { x: number; y: number }>;
  viewport?: { x: number; y: number; zoom: number };
  [key: string]: unknown;
}

// ─── Runtime status ─────────────────────────────────────────

export type OpusStatus = "stopped" | "starting" | "running" | "error";

// ─── Validation ─────────────────────────────────────────────

export interface ValidationError {
  code: string;
  message: string;
  target?: string;
}

// ─── Shared algorithms ──────────────────────────────────────

/**
 * Enrich dynamic output ports with typeFromPort mirrors.
 * For each dout_X, if a matching din_X exists in inputPorts,
 * adds typeFromPort so type inference propagates through.
 */
export function withDynamicMirrors(inputPorts: PortDef[], outputPorts: PortDef[]): PortDef[];

/** Minimal node representation for port type resolution. */
export interface ResolverNode {
  nid: string;
  inputPorts: PortDef[];
  outputPorts: PortDef[];
  configSchema: ConfigFieldSchema[];
  config: Record<string, unknown>;
}

/** Minimal link representation for graph algorithms. */
export interface ResolverLink {
  from: string;
  fromPort: string;
  to: string;
  toPort: string;
}

/**
 * Resolve effective port types for all nodes in a graph.
 * Runs connection inference, forward/reverse mirror propagation,
 * and respects frozen (typeFrom) ports.
 */
export function resolvePortTypes(
  nodes: ResolverNode[],
  links: ResolverLink[]
): Map<string, PortType>;

/**
 * Lightweight graph lint: detect unknown_kind and missing_config errors.
 * Suitable for client-side use without a server round-trip.
 */
export function lintGraph(
  nodes: Array<{ nid: string; kind: string; config: Record<string, unknown> }>,
  links: Array<{ to: string; toPort: string }>,
  kindMap: Map<string, NodeKindSchema>
): ValidationError[];
